theme: minima
title: Jonas Vindahl's Blog
description: A hacker-themed blog for my thoughts and updates.
markdown: kramdown
permalink: /:title/
sass:
  sass_dir: _sass
css_dir: assets/css
excerpt_separator: "\n\n" # This tells Jekyll to use the first paragraph break as the end of the excerpt.